// Linux apply orchestrator: a static POSIX shell script run by
// /bin/sh after the GUI process exits. Direct sibling of
// posix_apply_script.dart (macOS) — same argv-carries-all-values
// pattern (no quoting / injection surface), same bundle-swap
// semantics, adapted to what differs on Linux:
//
//   * The "install" is a single file (the .AppImage), not a
//     bundle tree — no ditto / extraction step. The staged file
//     IS the payload; it is hashed (TOCTOU close), made
//     executable, and renamed over the old AppImage.
//   * Renaming a mounted AppImage is safe: the squashfs loop
//     mount pins the INODE, so a running instance keeps its
//     image alive across the directory-entry swap exactly like
//     macOS keeps a swapped .app alive. The old file's inode only
//     dies when the aside is unlinked and the process exits.
//   * The relaunch must INHERIT the session environment (unlike
//     macOS's `env -i` scrub): a Linux GUI app needs
//     WAYLAND_DISPLAY / DISPLAY, XDG_RUNTIME_DIR and
//     DBUS_SESSION_BUS_ADDRESS to come up. The sh process is
//     spawned with the parent environment for exactly this
//     reason; no OCTODO_UPDATE_* vars exist on this path (values
//     travel as argv).
//   * coreutils only: sha256sum (not macOS's shasum), mv, cp,
//     chmod, cut, date, kill, sleep, nohup. /bin/sh and coreutils
//     are present on every distribution an AppImage targets.
//
// Sequence:
//   1. re-hash the staged file against the digest the GUI process
//      verified against the Ed25519 release signature (TOCTOU
//      close — the staging dir is user-writable),
//   2. wait (bounded) for the original app's pid to exit,
//   3. sweep stale `<appimage>.old-*` asides,
//   4. chmod +x; rename old aside, move new into place
//      (cross-device fallback: cp + rm, rollback on failure),
//   5. relaunch the new AppImage detached, inheriting the
//      session environment,
//   6. best-effort delete of the aside, sentinel log on success.
//
// Every failure path appends to the same octodo_apply_crash.log
// sentinel the macOS script and the Dart helper use.

import 'dart:io';

/// The static POSIX sh script. Runs with argv:
///
///   $1 original app pid
///   $2 staged AppImage path (already digest-verified)
///   $3 target AppImage path (the running $APPIMAGE)
///   $4 crash-sentinel log path
///   $5 expected SHA-256 hex ("" = skip the pre-swap re-hash;
///      only legacy/test callers pass "")
///
/// Keep [linuxApplyArgv] in sync with this list.
const String kLinuxApplyScript = r'''
#!/bin/sh
# Generated by octodo's in-app updater — do not edit.
# Linux AppImage file-swap apply; see lib/src/update/installer/linux_apply_script.dart.
set -u
PID="$1"; STAGED="$2"; TARGET="$3"; SENTINEL="$4"; SHA_EXPECTED="$5"

log() {
  printf '%s sh-apply: %s\n' "$(date '+%Y-%m-%dT%H:%M:%S')" "$1" \
    >> "$SENTINEL" 2>/dev/null || true
}
fail() { log "FAIL: $1"; exit 1; }

[ -f "$STAGED" ] || fail "staged AppImage missing: $STAGED"
[ -f "$TARGET" ] || fail "target AppImage missing: $TARGET"

# 0. TOCTOU close: re-hash the staged file against the digest the
#    GUI process verified against the release signature at
#    download time. The staging dir is user-writable; without
#    this, any same-user process could swap the file in the gap
#    between "verified" and "installed" and have the updater
#    execute it. Empty $SHA_EXPECTED (legacy callers) skips.
if [ -n "$SHA_EXPECTED" ]; then
  SHA_ACTUAL=$(sha256sum "$STAGED" | cut -d' ' -f1) \
    || fail "could not hash staged AppImage: $STAGED"
  [ "$SHA_ACTUAL" = "$SHA_EXPECTED" ] \
    || fail "staged AppImage digest changed after download: $SHA_ACTUAL != $SHA_EXPECTED"
  log "digest re-verified before swap: $SHA_ACTUAL"
fi

# 1. Bounded wait for the original app to exit (120 * 0.25 s =
#    30 s). The running AppImage's mount pins the inode, so
#    swapping the directory entry under a live process is safe;
#    the wait just avoids racing the GUI's own shutdown (state
#    flush, PTY sweeps) against the relaunch.
i=0
while kill -0 "$PID" 2>/dev/null && [ "$i" -lt 120 ]; do
  sleep 0.25
  i=$((i + 1))
done

# 2. Sweep stale asides from earlier interrupted swaps.
for f in "$TARGET".old-*; do
  [ -f "$f" ] && rm -f -- "$f" 2>/dev/null || true
done

# 3. Swap: executable bit first (the staged file may have landed
#    without one), then old aside, new into place. Same-directory
#    rename is atomic; the staging dir can legitimately live on a
#    different filesystem (~/.cache on another partition), so the
#    move falls back to a copy + delete.
chmod +x "$STAGED" || fail "cannot chmod staged AppImage: $STAGED"
ASIDE="$TARGET.old-$(date +%s)"
mv -f "$TARGET" "$ASIDE" || fail "cannot set aside running AppImage: $TARGET"
if ! mv "$STAGED" "$TARGET" 2>/dev/null; then
  # Cross-device staging (filesystem boundary): cp + rm instead.
  if cp "$STAGED" "$TARGET" && chmod +x "$TARGET"; then
    rm -f -- "$STAGED" 2>/dev/null || true
  else
    rm -f -- "$TARGET" 2>/dev/null
    mv -f "$ASIDE" "$TARGET" 2>/dev/null \
      || fail "rollback failed: $ASIDE -> $TARGET"
    fail "could not move new AppImage into place: $TARGET"
  fi
fi

# 4. Relaunch detached, inheriting the session environment (see
#    the file header: a scrubbed env would lose the Wayland /
#    D-Bus session and the relaunched app would die at startup).
#    The liveness probe window is diagnostics-only (the update is
#    already applied); 3 s covers a FUSE mount plus GTK init on
#    slower machines — a 1 s window logged spurious "relaunch
#    failed" lines for launches that came up moments later.
nohup "$TARGET" >/dev/null 2>&1 &
REL=$!
sleep 3
if ! kill -0 "$REL" 2>/dev/null; then
  log "relaunch failed for $TARGET (update applied; manual relaunch needed)"
fi

# 5. Best-effort aside cleanup; the next update's sweep catches it
#    if this fails (e.g. the old image is still mounted).
rm -f -- "$ASIDE" 2>/dev/null || true
log "OK: applied update to $TARGET from staging"
exit 0
''';

/// The argv (after the script path) [kLinuxApplyScript] expects.
/// Keep in lockstep with the `$1..$5` header comment above.
List<String> linuxApplyArgv({
  required int pid,
  required String stagedPath,
  required String targetPath,
  required String sentinelPath,
  String? expectedDigestHex,
}) {
  return <String>[
    pid.toString(),
    stagedPath,
    targetPath,
    sentinelPath,
    expectedDigestHex ?? '',
  ];
}

/// Signature of the process starter [spawnLinuxApply] uses.
/// Production wires Dart's [Process.start]; tests inject a
/// recorder so no /bin/sh is actually spawned.
typedef LinuxProcessStarter = Future<void> Function(
  String executable,
  List<String> arguments,
);

/// Write [script] and spawn `/bin/sh script <argv…>` detached.
/// Unlike the macOS spawn (posix_apply_script.dart), the child
/// INHERITS the parent environment — the relaunch inside the
/// script needs the desktop session's display / bus variables.
/// Returns when the script has been handed to the shell; the
/// swap itself happens after the caller exits. Throws on any
/// write/spawn failure; the caller surfaces an error while the
/// GUI is still alive.
Future<void> spawnLinuxApply({
  required int pid,
  required File stagedFile,
  required File targetFile,
  required File scriptFile,
  required File sentinelFile,
  String? expectedDigestHex,
  String script = kLinuxApplyScript,
  LinuxProcessStarter? starter,
}) async {
  await scriptFile.parent.create(recursive: true);
  await scriptFile.writeAsString(script, flush: true);
  await sentinelFile.parent.create(recursive: true);

  final argv = linuxApplyArgv(
    pid: pid,
    stagedPath: stagedFile.path,
    targetPath: targetFile.path,
    sentinelPath: sentinelFile.path,
    expectedDigestHex: expectedDigestHex,
  );

  final start = starter ?? _defaultStarter;
  await start('/bin/sh', <String>[scriptFile.path, ...argv]);
}

Future<void> _defaultStarter(
  String executable,
  List<String> arguments,
) async {
  await Process.start(
    executable,
    arguments,
    // Deliberately inherits the parent (session) environment —
    // see the doc comment above.
    includeParentEnvironment: true,
    mode: ProcessStartMode.detached,
  );
}
