// macOS apply orchestrator: a static POSIX shell script run by
// /bin/sh after the GUI process exits.
//
// WHY A SHELL SCRIPT (and not the bundled Dart helper):
// `octodo_helper` is a `dart compile exe` AOT binary. The Dart AOT
// runtime writes to its own code pages while booting the snapshot;
// under macOS Hardened Runtime the kernel enforces W^X on code
// pages and kills the process ~50 ms after exec with
//
//   kernel: CODE SIGNING: process N[octodo_helper]:
//   rejecting invalid page ... (signed:0 validated:0 wpmapped:1)
//
// — observed killing every macOS apply attempt on a
// Developer-ID-signed, hardened-runtime build (Aug 2026; the app
// quits, nothing is applied, manual relaunch shows the old
// version). cmux (Sparkle) avoids this class of failure because
// every image its updater execs is native, properly-entitled,
// notarized code; a Dart AOT binary cannot make that claim.
//
// The fix: exec only binaries Apple signed themselves. /bin/sh is
// part of the OS and exempt from Gatekeeper assessment and HR
// quirks; ditto / xattr / open are Apple tools present on every
// macOS install. The GUI app writes this script into the update
// staging dir and spawns `/bin/sh <script> <args…>` detached, then
// exits. All runtime values (paths, pid) travel as positional
// arguments — the script body is fully static, so there is no
// quoting / injection surface.
//
// The script mirrors StagedApply's bundleSwap semantics:
//   1. wait (bounded) for the original app's pid to exit,
//   2. extract the staged zip with ditto (restores framework
//      symlinks + exec bits),
//   3. strip quarantine-ish xattrs from the new bundle,
//   4. sweep stale `<bundle>.old-*` asides,
//   5. rename the old bundle aside, move the new one into place
//      (cross-volume fallback: recursive ditto copy), rollback on
//      failure,
//   6. relaunch via Launch Services (`open`) with a scrubbed env,
//   7. best-effort delete of the aside, sentinel log on success.
//
// Every failure path appends to the same octodo_apply_crash.log
// sentinel the Dart helper uses, so a dead apply is diagnosable
// after the fact.

import 'dart:io';

/// The static POSIX sh script. Runs with argv:
///
///   $1 original app pid        $5 crash-sentinel log path
///   $2 staged zip path         $6 HOME for the relaunched app
///   $3 extract dir             $7 expected SHA-256 hex ("" = skip
///   $4 current .app bundle path    the pre-extract re-hash; only
///                                  legacy/test callers pass "")
///                              $8 codesign designated requirement
///                                 ("" = skip the payload signature
///                                 gate; the controller passes it
///                                 only when the running bundle
///                                 satisfies the pin itself)
///
/// Keep [posixApplyArgv] in sync with this list.
const String kPosixApplyScript = r'''
#!/bin/sh
# Generated by octodo's in-app updater — do not edit.
# macOS bundle-swap apply; see lib/src/update/installer/posix_apply_script.dart.
set -u
PID="$1"; ZIP="$2"; EXTRACT="$3"; BUNDLE="$4"; SENTINEL="$5"; HOME_DIR="$6"; SHA_EXPECTED="$7"; REQ="$8"

log() {
  printf '%s sh-apply: %s\n' "$(date '+%Y-%m-%dT%H:%M:%S')" "$1" \
    >> "$SENTINEL" 2>/dev/null || true
}
fail() { log "FAIL: $1"; exit 1; }

[ -f "$ZIP" ] || fail "staged zip missing: $ZIP"

# 0. TOCTOU close (GH issue #5, item 4): re-hash the staged zip
#    against the digest the GUI process verified against the release
#    signature at download time. The staging dir is user-writable;
#    without this, any same-user process could swap the file in the
#    gap between "verified" and "extracted" and have the updater
#    install it. Empty $SHA_EXPECTED (legacy callers) skips.
if [ -n "$SHA_EXPECTED" ]; then
  SHA_ACTUAL=$(/usr/bin/shasum -a 256 "$ZIP" | /usr/bin/cut -d' ' -f1) \
    || fail "could not hash staged zip: $ZIP"
  [ "$SHA_ACTUAL" = "$SHA_EXPECTED" ] \
    || fail "staged zip digest changed after download: $SHA_ACTUAL != $SHA_EXPECTED"
  log "digest re-verified before extract: $SHA_ACTUAL"
fi

# 1. Bounded wait for the original app to exit (120 * 0.25 s = 30 s).
#    POSIX never write-locks the bundle, so proceeding after the
#    ceiling is harmless (the running binary's inode survives
#    renames); the wait just avoids swapping under a live app.
i=0
while kill -0 "$PID" 2>/dev/null && [ "$i" -lt 120 ]; do
  sleep 0.25
  i=$((i + 1))
done

# 2. Fresh extract dir; ditto restores symlinks + unix modes that
#    the ditto-created release zip carries.
rm -rf "$EXTRACT" 2>/dev/null || true
mkdir -p "$EXTRACT" || fail "cannot create extract dir: $EXTRACT"
/usr/bin/ditto -x -k --rsrc "$ZIP" "$EXTRACT" \
  || fail "ditto extract failed for $ZIP"

# Locate the payload's .app by SHAPE, not by name — the release
# zip always carries `Octodo.app`, but the *running* bundle may
# have been renamed (side-by-side installs like "Octodo 2.app").
# Exactly one .app at the extract root is the contract (same as
# the Dart path's _findSingleAppBundle); zero or many → refuse
# rather than guess.
NEW=""
for d in "$EXTRACT"/*.app; do
  if [ -d "$d" ]; then
    if [ -n "$NEW" ]; then
      fail "multiple .app bundles at extract root: $EXTRACT"
    fi
    NEW="$d"
  fi
done
[ -n "$NEW" ] || fail "no .app bundle at extract root: $EXTRACT"

# 3. Payload code-signature gate (Phase C): the new bundle must
#    satisfy the pinned designated requirement (Developer ID Team)
#    BEFORE any quarantine-xattr stripping or swap happens — on
#    failure the running bundle is untouched. Empty $REQ (dev
#    builds, forks, legacy callers) skips the gate; the Ed25519
#    manifest signature verified at download time still applies.
if [ -n "$REQ" ]; then
  /usr/bin/codesign --verify --deep --strict -R="$REQ" "$NEW" \
    || fail "new bundle failed code signature verification (req: $REQ)"
  log "payload code signature verified"
fi

# 4. Belt-and-braces Gatekeeper hygiene: bytes downloaded in-app
#    never get a quarantine xattr, but a user-forwarded zip could.
/usr/bin/xattr -cr "$NEW" 2>/dev/null || true

# 5. Sweep stale asides from earlier interrupted swaps.
for d in "$BUNDLE".old-*; do
  [ -d "$d" ] && rm -rf -- "$d" 2>/dev/null || true
done

# 6. Swap: old bundle aside, new bundle into its name.
ASIDE="$BUNDLE.old-$(date +%s)"
mv "$BUNDLE" "$ASIDE" || fail "cannot set aside running bundle: $BUNDLE"
if ! mv "$NEW" "$BUNDLE" 2>/dev/null; then
  # Cross-device staging (volume boundary): ditto-copy instead.
  if /usr/bin/ditto "$NEW" "$BUNDLE"; then
    rm -rf -- "$NEW" 2>/dev/null || true
  else
    rm -rf -- "$BUNDLE" 2>/dev/null || true
    mv "$ASIDE" "$BUNDLE" 2>/dev/null \
      || fail "rollback failed: $ASIDE -> $BUNDLE"
    fail "could not move new bundle into place: $BUNDLE"
  fi
fi

# 7. Relaunch through Launch Services (activation semantics match a
#    user launch; Sparkle/cmux do the same). `open` forwards the
#    caller's environment, so run it under `env -i` with only HOME
#    and PATH — this sh inherits no OCTODO_UPDATE_* vars (values
#    arrive as argv), but scrubbing keeps the relaunched app's env
#    identical to a clean login-session launch.
if ! env -i HOME="$HOME_DIR" PATH=/usr/bin:/bin /usr/bin/open "$BUNDLE"; then
  log "open failed for $BUNDLE (update applied; manual relaunch needed)"
fi

# 8. Best-effort aside cleanup; the next update's sweep catches it
#    if this fails.
rm -rf -- "$ASIDE" 2>/dev/null || true
log "OK: applied update from $ZIP"
exit 0
''';

/// The argv (after the script path) [kPosixApplyScript] expects.
/// Keep in lockstep with the `$1..$8` header comment above.
List<String> posixApplyArgv({
  required int pid,
  required String zipPath,
  required String extractDirPath,
  required String bundlePath,
  required String sentinelPath,
  required String homeDir,
  String? expectedDigestHex,
  String? codeSignRequirement,
}) {
  return <String>[
    pid.toString(),
    zipPath,
    extractDirPath,
    bundlePath,
    sentinelPath,
    homeDir,
    expectedDigestHex ?? '',
    codeSignRequirement ?? '',
  ];
}

/// Signature of the process starter [spawnPosixApply] uses.
/// Production wires Dart's [Process.start]; tests inject a
/// recorder so no /bin/sh is actually spawned.
typedef PosixProcessStarter = Future<void> Function(
  String executable,
  List<String> arguments,
);

/// Write [script] and spawn `/bin/sh script <argv…>` detached with
/// a minimal environment (PATH/HOME only). Returns when the script
/// has been handed to the shell — the swap itself happens after
/// the caller exits. Throws on any write/spawn failure; the caller
/// surfaces an error while the GUI is still alive.
Future<void> spawnPosixApply({
  required int pid,
  required File zipFile,
  required Directory extractDir,
  required Directory bundleRoot,
  required File scriptFile,
  required File sentinelFile,
  required String homeDir,
  String? expectedDigestHex,
  String? codeSignRequirement,
  String script = kPosixApplyScript,
  PosixProcessStarter? starter,
}) async {
  await scriptFile.parent.create(recursive: true);
  await scriptFile.writeAsString(script, flush: true);
  await sentinelFile.parent.create(recursive: true);

  final argv = posixApplyArgv(
    pid: pid,
    zipPath: zipFile.path,
    extractDirPath: extractDir.path,
    bundlePath: bundleRoot.path,
    sentinelPath: sentinelFile.path,
    homeDir: homeDir,
    expectedDigestHex: expectedDigestHex,
    codeSignRequirement: codeSignRequirement,
  );

  final start = starter ?? _defaultStarter;
  await start('/bin/sh', <String>[scriptFile.path, ...argv]);
}

Future<void> _defaultStarter(String executable, List<String> arguments) async {
  await Process.start(
    executable,
    arguments,
    // Minimal env: the script only needs /usr/bin:/bin, and a clean
    // environment guarantees no OCTODO_UPDATE_* leakage into the
    // relaunched app via `open`'s env forwarding.
    includeParentEnvironment: false,
    environment: const <String, String>{
      'PATH': '/usr/bin:/bin',
    },
    mode: ProcessStartMode.detached,
  );
}
