// GitHub release JSON resolver + asset matcher.
//
// The /repos/{owner}/{repo}/releases/latest endpoint returns a single
// release payload. We extract:
//   * `tag_name` ("v1.2.3") stripped of leading "v" → version.
//   * `prerelease` (informational; /releases/latest already filters
//     pre-releases, so this is the strict-stable case in practice).
//   * `published_at` (display only).
//   * `html_url` (release notes page).
//   * The asset matching `^octodo-v<ver>-windows-x64\.zip$` (zip).
//   * Sibling asset matching `^octodo-v<ver>-windows-x64\.zip\.sha256$`
//     (digest sidecar, optional — older releases may lack it).
//
// We re-derive the version from each asset filename and require it
// to match `tag_name` — guards against an asset uploaded under the
// wrong tag after publishing.
//
// Pure function: no I/O, no globals, fully testable. The HTTP client
// (separate file) fetches the body; this file parses it.

import 'dart:convert';

/// Strict regex matching the install asset filename. Captures the
/// "X.Y.Z" or "X.Y.Z-prerelease" version portion for cross-checking
/// against the release tag.
final RegExp kWindowsAssetPattern = RegExp(
  r'^octodo-v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)-windows-x64\.zip$',
);

/// Strict regex matching the digest sidecar asset. Captures the same
/// version portion.
final RegExp kWindowsAssetSha256Pattern = RegExp(
  r'^octodo-v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)-windows-x64\.zip\.sha256$',
);

/// Conservative semver-shape check. Accepts the same shape the
/// release workflow accepts: "X.Y.Z" or "X.Y.Z-prerelease".
final RegExp _kSemverShape = RegExp(
  r'^\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?$',
);

class ResolverException implements Exception {
  final String message;
  final Object? cause;
  const ResolverException(this.message, [this.cause]);

  @override
  String toString() => cause == null
      ? 'ResolverException: $message'
      : 'ResolverException: $message ($cause)';
}

/// A resolved GitHub release with the matching Windows build asset
/// identified, ready to be downloaded and verified. Constructed by
/// [resolveReleaseJson]; never mutated after construction.
class ReleaseInfo {
  /// "X.Y.Z" or "X.Y.Z-prerelease" — what the running app will
  /// compare against its own version via `compareSemver`.
  final String version;

  /// Raw tag name as published, including any "v" prefix.
  final String tagName;

  /// Whether GitHub marked this as a pre-release. /releases/latest
  /// is supposed to filter these out, so this is informational but
  /// logged for diagnostics.
  final bool prerelease;

  /// `published_at` field, parsed. Display-only; may be null.
  final DateTime? publishedAt;

  /// The release page (notesUrl in the legacy manifest model).
  final Uri htmlUrl;

  /// Direct download URL of the matched zip asset.
  final Uri zipUrl;

  /// Reported size of the zip asset in bytes (used for progress UI).
  final int zipSizeBytes;

  /// Direct download URL of the matched .sha256 sidecar, or null
  /// when the release was published without one (older releases, or
  /// a future asset that wasn't generated by the workflow).
  final Uri? digestUrl;

  /// Release notes body (markdown), or null if GitHub didn't include
  /// one. We don't render this in v1 but expose it for future use.
  final String? body;

  const ReleaseInfo({
    required this.version,
    required this.tagName,
    required this.prerelease,
    required this.htmlUrl,
    required this.zipUrl,
    required this.zipSizeBytes,
    this.publishedAt,
    this.digestUrl,
    this.body,
  });
}

/// Parse a GitHub release JSON body into a [ReleaseInfo]. Throws
/// [ResolverException] on any structural problem — a release without
/// a matching Windows asset surfaces a clear error to the controller
/// instead of being silently dropped.
ReleaseInfo resolveReleaseJson(String body) {
  final decoded = jsonDecode(body);
  if (decoded is! Map<String, dynamic>) {
    throw ResolverException(
      'Expected JSON object at root, got ${decoded.runtimeType}',
    );
  }
  return resolveReleaseMap(decoded);
}

/// Like [resolveReleaseJson] but takes the already-decoded Map. Useful
/// for tests that bypass JSON encoding.
ReleaseInfo resolveReleaseMap(Map<String, dynamic> json) {
  final tagName = json['tag_name'];
  if (tagName is! String || tagName.isEmpty) {
    throw const ResolverException('Missing or empty "tag_name"');
  }
  final version = tagName.startsWith('v')
      ? tagName.substring(1)
      : tagName;
  if (!_kSemverShape.hasMatch(version)) {
    throw ResolverException(
      'Tag "$tagName" is not shaped like vX.Y.Z or vX.Y.Z-prerelease',
    );
  }

  final prereleaseRaw = json['prerelease'];
  if (prereleaseRaw is! bool) {
    throw const ResolverException('"prerelease" must be a boolean');
  }

  final publishedAtRaw = json['published_at'];
  DateTime? publishedAt;
  if (publishedAtRaw is String && publishedAtRaw.isNotEmpty) {
    publishedAt = DateTime.tryParse(publishedAtRaw);
  }

  final htmlUrlRaw = json['html_url'];
  if (htmlUrlRaw is! String || htmlUrlRaw.isEmpty) {
    throw const ResolverException('Missing or empty "html_url"');
  }
  final htmlUrl = Uri.tryParse(htmlUrlRaw);
  if (htmlUrl == null || !htmlUrl.hasScheme) {
    throw ResolverException('Invalid "html_url": $htmlUrlRaw');
  }

  final body = json['body'] is String ? json['body'] as String : null;

  final assetsRaw = json['assets'];
  if (assetsRaw is! List) {
    throw const ResolverException('"assets" must be an array');
  }

  Uri? zipUrl;
  int? zipSize;
  Uri? digestUrl;

  for (final entry in assetsRaw) {
    if (entry is! Map<String, dynamic>) continue;
    final name = entry['name'];
    if (name is! String) continue;

    final shaMatch = kWindowsAssetSha256Pattern.firstMatch(name);
    if (shaMatch != null) {
      if (shaMatch.group(1) != version) continue;
      digestUrl = _assetDownloadUrl(entry, hint: 'digest asset');
      continue;
    }

    final zipMatch = kWindowsAssetPattern.firstMatch(name);
    if (zipMatch != null) {
      if (zipMatch.group(1) != version) continue;
      zipUrl = _assetDownloadUrl(entry, hint: 'zip asset');
      final sizeRaw = entry['size'];
      zipSize = sizeRaw is int ? sizeRaw : 0;
      continue;
    }
  }

  if (zipUrl == null) {
    throw ResolverException(
      'Release $tagName has no asset matching ${kWindowsAssetPattern.pattern}',
    );
  }

  return ReleaseInfo(
    version: version,
    tagName: tagName,
    prerelease: prereleaseRaw,
    publishedAt: publishedAt,
    htmlUrl: htmlUrl,
    zipUrl: zipUrl,
    zipSizeBytes: zipSize ?? 0,
    digestUrl: digestUrl,
    body: body,
  );
}

Uri? _assetDownloadUrl(
  Map<String, dynamic> asset, {
  required String hint,
}) {
  final raw = asset['browser_download_url'];
  if (raw is! String || raw.isEmpty) {
    throw ResolverException(
      '$hint has missing/empty browser_download_url',
    );
  }
  final uri = Uri.tryParse(raw);
  if (uri == null || !uri.hasScheme) {
    throw ResolverException(
      '$hint has invalid browser_download_url: $raw',
    );
  }
  return uri;
}
